//
//  Language.swift
//  Translator
//
//  Created by truID on 11/03/2025.
//

import Foundation

struct Language: Identifiable {
    let id = UUID()
    let name: String
    let code: String
}

let languages: [Language] = [
    Language(name: "Abkhaz", code: "ab"),
    Language(name: "Acehnese", code: "ace"),
    Language(name: "Acholi", code: "ach"),
    Language(name: "Afrikaans", code: "af"),
    Language(name: "Albanian", code: "sq"),
    Language(name: "Alur", code: "alz"),
    Language(name: "Amharic", code: "am"),
    Language(name: "Arabic", code: "ar"),
    Language(name: "Armenian", code: "hy"),
    Language(name: "Assamese", code: "as"),
    Language(name: "Awadhi", code: "awa"),
    Language(name: "Aymara", code: "ay"),
    Language(name: "Azerbaijani", code: "az"),
    Language(name: "Balinese", code: "ban"),
    Language(name: "Bambara", code: "bm"),
    Language(name: "Bashkir", code: "ba"),
    Language(name: "Basque", code: "eu"),
    Language(name: "Batak Karo", code: "btx"),
    Language(name: "Batak Simalungun", code: "bts"),
    Language(name: "Batak Toba", code: "bbc"),
    Language(name: "Belarusian", code: "be"),
    Language(name: "Bemba", code: "bem"),
    Language(name: "Bengali", code: "bn"),
    Language(name: "Betawi", code: "bew"),
    Language(name: "Bhojpuri", code: "bho"),
    Language(name: "Bikol", code: "bik"),
    Language(name: "Bosnian", code: "bs"),
    Language(name: "Breton", code: "br"),
    Language(name: "Bulgarian", code: "bg"),
    Language(name: "Buryat", code: "bua"),
    Language(name: "Cantonese", code: "yue"),
    Language(name: "Catalan", code: "ca"),
    Language(name: "Cebuano", code: "ceb"),
    Language(name: "Chichewa (Nyanja)", code: "ny"),
    Language(name: "Chinese (Simplified)", code: "zh-CN"),
    Language(name: "Chinese (Traditional)", code: "zh-TW"),
    Language(name: "Chuvash", code: "cv"),
    Language(name: "Corsican", code: "co"),
    Language(name: "Crimean Tatar", code: "crh"),
    Language(name: "Croatian", code: "hr"),
    Language(name: "Czech", code: "cs"),
    Language(name: "Danish", code: "da"),
    Language(name: "Dinka", code: "din"),
    Language(name: "Divehi", code: "dv"),
    Language(name: "Dogri", code: "doi"),
    Language(name: "Dombe", code: "dov"),
    Language(name: "Dutch", code: "nl"),
    Language(name: "Dzongkha", code: "dz"),
    Language(name: "English", code: "en"),
    Language(name: "Esperanto", code: "eo"),
    Language(name: "Estonian", code: "et"),
    Language(name: "Ewe", code: "ee"),
    Language(name: "Fijian", code: "fj"),
    Language(name: "Filipino (Tagalog)", code: "fil"),
    Language(name: "Finnish", code: "fi"),
    Language(name: "French", code: "fr"),
    Language(name: "French (French)", code: "fr-FR"),
    Language(name: "French (Canadian)", code: "fr-CA"),
    Language(name: "Frisian", code: "fy"),
    Language(name: "Fulfulde", code: "ff"),
    Language(name: "Ga", code: "gaa"),
    Language(name: "Galician", code: "gl"),
    Language(name: "Ganda (Luganda)", code: "lg"),
    Language(name: "Georgian", code: "ka"),
    Language(name: "German", code: "de"),
    Language(name: "Greek", code: "el"),
    Language(name: "Guarani", code: "gn"),
    Language(name: "Gujarati", code: "gu"),
    Language(name: "Haitian Creole", code: "ht"),
    Language(name: "Hakha Chin", code: "cnh"),
    Language(name: "Hausa", code: "ha"),
    Language(name: "Hawaiian", code: "haw"),
    Language(name: "Hebrew", code: "he"),
    Language(name: "Hiligaynon", code: "hil"),
    Language(name: "Hindi", code: "hi"),
    Language(name: "Hmong", code: "hmn"),
    Language(name: "Hungarian", code: "hu"),
    Language(name: "Icelandic", code: "is"),
    Language(name: "Igbo", code: "ig"),
    Language(name: "Iloko", code: "ilo"),
    Language(name: "Indonesian", code: "id"),
    Language(name: "Irish", code: "ga"),
    Language(name: "Italian", code: "it"),
    Language(name: "Japanese", code: "ja"),
    Language(name: "Javanese", code: "jv"),
    Language(name: "Kannada", code: "kn"),
    Language(name: "Kazakh", code: "kk"),
    Language(name: "Khmer", code: "km"),
    Language(name: "Kinyarwanda", code: "rw"),
    Language(name: "Korean", code: "ko"),
    Language(name: "Kurdish (Kurmanji)", code: "ku"),
    Language(name: "Kurdish (Sorani)", code: "ckb"),
    Language(name: "Lao", code: "lo"),
    Language(name: "Latin", code: "la"),
    Language(name: "Latvian", code: "lv"),
    Language(name: "Lithuanian", code: "lt"),
    Language(name: "Luxembourgish", code: "lb"),
    Language(name: "Macedonian", code: "mk"),
    Language(name: "Malay", code: "ms"),
    Language(name: "Malayalam", code: "ml"),
    Language(name: "Maltese", code: "mt"),
    Language(name: "Maori", code: "mi"),
    Language(name: "Marathi", code: "mr"),
    Language(name: "Mongolian", code: "mn"),
    Language(name: "Myanmar (Burmese)", code: "my"),
    Language(name: "Nepali", code: "ne"),
    Language(name: "Norwegian", code: "no"),
    Language(name: "Pashto", code: "ps"),
    Language(name: "Persian", code: "fa"),
    Language(name: "Polish", code: "pl"),
    Language(name: "Portuguese", code: "pt"),
    Language(name: "Punjabi", code: "pa"),
    Language(name: "Russian", code: "ru"),
    Language(name: "Samoan", code: "sm"),
    Language(name: "Sango", code: "sg"),
    Language(name: "Sanskrit", code: "sa"),
    Language(name: "Scots Gaelic", code: "gd"),
    Language(name: "Serbian", code: "sr"),
    Language(name: "Sesotho", code: "st"),
    Language(name: "Seychellois Creole", code: "crs"),
    Language(name: "Shan", code: "shn"),
    Language(name: "Shona", code: "sn"),
    Language(name: "Sicilian", code: "scn"),
    Language(name: "Silesian", code: "szl"),
    Language(name: "Sindhi", code: "sd"),
    Language(name: "Sinhala (Sinhalese)", code: "si"),
    Language(name: "Slovak", code: "sk"),
    Language(name: "Slovenian", code: "sl"),
    Language(name: "Somali", code: "so"),
    Language(name: "Spanish", code: "es"),
    Language(name: "Sundanese", code: "su"),
    Language(name: "Swahili", code: "sw"),
    Language(name: "Swati", code: "ss"),
    Language(name: "Swedish", code: "sv"),
    Language(name: "Tajik", code: "tg"),
    Language(name: "Tamil", code: "ta"),
    Language(name: "Tatar", code: "tt"),
    Language(name: "Telugu", code: "te"),
    Language(name: "Tetum", code: "tet"),
    Language(name: "Thai", code: "th"),
    Language(name: "Tigrinya", code: "ti"),
    Language(name: "Tsonga", code: "ts"),
    Language(name: "Tswana", code: "tn"),
    Language(name: "Turkish", code: "tr"),
    Language(name: "Turkmen", code: "tk"),
    Language(name: "Twi (Akan)", code: "ak"),
    Language(name: "Ukrainian", code: "uk"),
    Language(name: "Urdu", code: "ur"),
    Language(name: "Uyghur", code: "ug"),
    Language(name: "Uzbek", code: "uz"),
    Language(name: "Vietnamese", code: "vi"),
    Language(name: "Welsh", code: "cy"),
    Language(name: "Xhosa", code: "xh"),
    Language(name: "Yiddish", code: "yi"),
    Language(name: "Yoruba", code: "yo"),
    Language(name: "Yucatec Maya", code: "yua"),
    Language(name: "Zulu", code: "zu")
]
